language: java

jdk: openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ab434b05-271d-4269-afc6-fbbde4dcef6d
